name: gen-artifacts
on:
   workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  REGISTRY: registry.cn-shenzhen.aliyuncs.com/cnmirror

jobs:
  kubespray:
    runs-on: ubuntu-22.04     
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
  
      - name: Login to Aliyun Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.ubuntu2204
          push: true
          tags: ${{ env.REGISTRY }}/kubernetes:${{ env.KUBERNETES_VERSION }}-${{ env.PACKAGE_VERSION }}
          build-args: |
            KUBESPRAY_VERSION=${{ env.KUBESPRAY_VERSION }}
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
            PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
